# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/djrussell23/Documents/repos/reactor-core

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/djrussell23/Documents/repos/reactor-core

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd /Users/djrussell23/Documents/repos/reactor-core && $(CMAKE_COMMAND) -E cmake_progress_start /Users/djrussell23/Documents/repos/reactor-core/CMakeFiles /Users/djrussell23/Documents/repos/reactor-core/mlforge//CMakeFiles/progress.marks
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mlforge/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/djrussell23/Documents/repos/reactor-core/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mlforge/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mlforge/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mlforge/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
mlforge/CMakeFiles/MLForgeLib.dir/rule:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mlforge/CMakeFiles/MLForgeLib.dir/rule
.PHONY : mlforge/CMakeFiles/MLForgeLib.dir/rule

# Convenience name for target.
MLForgeLib: mlforge/CMakeFiles/MLForgeLib.dir/rule
.PHONY : MLForgeLib

# fast build rule for target.
MLForgeLib/fast:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/build
.PHONY : MLForgeLib/fast

# Convenience name for target.
mlforge/CMakeFiles/test_algorithms.dir/rule:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mlforge/CMakeFiles/test_algorithms.dir/rule
.PHONY : mlforge/CMakeFiles/test_algorithms.dir/rule

# Convenience name for target.
test_algorithms: mlforge/CMakeFiles/test_algorithms.dir/rule
.PHONY : test_algorithms

# fast build rule for target.
test_algorithms/fast:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/test_algorithms.dir/build.make mlforge/CMakeFiles/test_algorithms.dir/build
.PHONY : test_algorithms/fast

# Convenience name for target.
mlforge/CMakeFiles/test_linear_regression.dir/rule:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mlforge/CMakeFiles/test_linear_regression.dir/rule
.PHONY : mlforge/CMakeFiles/test_linear_regression.dir/rule

# Convenience name for target.
test_linear_regression: mlforge/CMakeFiles/test_linear_regression.dir/rule
.PHONY : test_linear_regression

# fast build rule for target.
test_linear_regression/fast:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/test_linear_regression.dir/build.make mlforge/CMakeFiles/test_linear_regression.dir/build
.PHONY : test_linear_regression/fast

# Convenience name for target.
mlforge/CMakeFiles/test_logistic_regression.dir/rule:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mlforge/CMakeFiles/test_logistic_regression.dir/rule
.PHONY : mlforge/CMakeFiles/test_logistic_regression.dir/rule

# Convenience name for target.
test_logistic_regression: mlforge/CMakeFiles/test_logistic_regression.dir/rule
.PHONY : test_logistic_regression

# fast build rule for target.
test_logistic_regression/fast:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/test_logistic_regression.dir/build.make mlforge/CMakeFiles/test_logistic_regression.dir/build
.PHONY : test_logistic_regression/fast

# Convenience name for target.
mlforge/CMakeFiles/benchmarks.dir/rule:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mlforge/CMakeFiles/benchmarks.dir/rule
.PHONY : mlforge/CMakeFiles/benchmarks.dir/rule

# Convenience name for target.
benchmarks: mlforge/CMakeFiles/benchmarks.dir/rule
.PHONY : benchmarks

# fast build rule for target.
benchmarks/fast:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/benchmarks.dir/build.make mlforge/CMakeFiles/benchmarks.dir/build
.PHONY : benchmarks/fast

# Convenience name for target.
mlforge/CMakeFiles/profiler.dir/rule:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mlforge/CMakeFiles/profiler.dir/rule
.PHONY : mlforge/CMakeFiles/profiler.dir/rule

# Convenience name for target.
profiler: mlforge/CMakeFiles/profiler.dir/rule
.PHONY : profiler

# fast build rule for target.
profiler/fast:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/profiler.dir/build.make mlforge/CMakeFiles/profiler.dir/build
.PHONY : profiler/fast

benchmarks/benchmarks.o: benchmarks/benchmarks.cpp.o
.PHONY : benchmarks/benchmarks.o

# target to build an object file
benchmarks/benchmarks.cpp.o:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/benchmarks.dir/build.make mlforge/CMakeFiles/benchmarks.dir/benchmarks/benchmarks.cpp.o
.PHONY : benchmarks/benchmarks.cpp.o

benchmarks/benchmarks.i: benchmarks/benchmarks.cpp.i
.PHONY : benchmarks/benchmarks.i

# target to preprocess a source file
benchmarks/benchmarks.cpp.i:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/benchmarks.dir/build.make mlforge/CMakeFiles/benchmarks.dir/benchmarks/benchmarks.cpp.i
.PHONY : benchmarks/benchmarks.cpp.i

benchmarks/benchmarks.s: benchmarks/benchmarks.cpp.s
.PHONY : benchmarks/benchmarks.s

# target to generate assembly for a file
benchmarks/benchmarks.cpp.s:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/benchmarks.dir/build.make mlforge/CMakeFiles/benchmarks.dir/benchmarks/benchmarks.cpp.s
.PHONY : benchmarks/benchmarks.cpp.s

profiling/profiler.o: profiling/profiler.cpp.o
.PHONY : profiling/profiler.o

# target to build an object file
profiling/profiler.cpp.o:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/profiler.dir/build.make mlforge/CMakeFiles/profiler.dir/profiling/profiler.cpp.o
.PHONY : profiling/profiler.cpp.o

profiling/profiler.i: profiling/profiler.cpp.i
.PHONY : profiling/profiler.i

# target to preprocess a source file
profiling/profiler.cpp.i:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/profiler.dir/build.make mlforge/CMakeFiles/profiler.dir/profiling/profiler.cpp.i
.PHONY : profiling/profiler.cpp.i

profiling/profiler.s: profiling/profiler.cpp.s
.PHONY : profiling/profiler.s

# target to generate assembly for a file
profiling/profiler.cpp.s:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/profiler.dir/build.make mlforge/CMakeFiles/profiler.dir/profiling/profiler.cpp.s
.PHONY : profiling/profiler.cpp.s

src/ai/nlp_transformer.o: src/ai/nlp_transformer.cpp.o
.PHONY : src/ai/nlp_transformer.o

# target to build an object file
src/ai/nlp_transformer.cpp.o:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/ai/nlp_transformer.cpp.o
.PHONY : src/ai/nlp_transformer.cpp.o

src/ai/nlp_transformer.i: src/ai/nlp_transformer.cpp.i
.PHONY : src/ai/nlp_transformer.i

# target to preprocess a source file
src/ai/nlp_transformer.cpp.i:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/ai/nlp_transformer.cpp.i
.PHONY : src/ai/nlp_transformer.cpp.i

src/ai/nlp_transformer.s: src/ai/nlp_transformer.cpp.s
.PHONY : src/ai/nlp_transformer.s

# target to generate assembly for a file
src/ai/nlp_transformer.cpp.s:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/ai/nlp_transformer.cpp.s
.PHONY : src/ai/nlp_transformer.cpp.s

src/algorithms/decision.tree.o: src/algorithms/decision.tree.cpp.o
.PHONY : src/algorithms/decision.tree.o

# target to build an object file
src/algorithms/decision.tree.cpp.o:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/algorithms/decision.tree.cpp.o
.PHONY : src/algorithms/decision.tree.cpp.o

src/algorithms/decision.tree.i: src/algorithms/decision.tree.cpp.i
.PHONY : src/algorithms/decision.tree.i

# target to preprocess a source file
src/algorithms/decision.tree.cpp.i:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/algorithms/decision.tree.cpp.i
.PHONY : src/algorithms/decision.tree.cpp.i

src/algorithms/decision.tree.s: src/algorithms/decision.tree.cpp.s
.PHONY : src/algorithms/decision.tree.s

# target to generate assembly for a file
src/algorithms/decision.tree.cpp.s:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/algorithms/decision.tree.cpp.s
.PHONY : src/algorithms/decision.tree.cpp.s

src/algorithms/linear_regression.o: src/algorithms/linear_regression.cpp.o
.PHONY : src/algorithms/linear_regression.o

# target to build an object file
src/algorithms/linear_regression.cpp.o:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/algorithms/linear_regression.cpp.o
.PHONY : src/algorithms/linear_regression.cpp.o

src/algorithms/linear_regression.i: src/algorithms/linear_regression.cpp.i
.PHONY : src/algorithms/linear_regression.i

# target to preprocess a source file
src/algorithms/linear_regression.cpp.i:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/algorithms/linear_regression.cpp.i
.PHONY : src/algorithms/linear_regression.cpp.i

src/algorithms/linear_regression.s: src/algorithms/linear_regression.cpp.s
.PHONY : src/algorithms/linear_regression.s

# target to generate assembly for a file
src/algorithms/linear_regression.cpp.s:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/algorithms/linear_regression.cpp.s
.PHONY : src/algorithms/linear_regression.cpp.s

src/algorithms/logistic_regression.o: src/algorithms/logistic_regression.cpp.o
.PHONY : src/algorithms/logistic_regression.o

# target to build an object file
src/algorithms/logistic_regression.cpp.o:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/algorithms/logistic_regression.cpp.o
.PHONY : src/algorithms/logistic_regression.cpp.o

src/algorithms/logistic_regression.i: src/algorithms/logistic_regression.cpp.i
.PHONY : src/algorithms/logistic_regression.i

# target to preprocess a source file
src/algorithms/logistic_regression.cpp.i:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/algorithms/logistic_regression.cpp.i
.PHONY : src/algorithms/logistic_regression.cpp.i

src/algorithms/logistic_regression.s: src/algorithms/logistic_regression.cpp.s
.PHONY : src/algorithms/logistic_regression.s

# target to generate assembly for a file
src/algorithms/logistic_regression.cpp.s:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/algorithms/logistic_regression.cpp.s
.PHONY : src/algorithms/logistic_regression.cpp.s

src/algorithms/neural_net.o: src/algorithms/neural_net.cpp.o
.PHONY : src/algorithms/neural_net.o

# target to build an object file
src/algorithms/neural_net.cpp.o:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/algorithms/neural_net.cpp.o
.PHONY : src/algorithms/neural_net.cpp.o

src/algorithms/neural_net.i: src/algorithms/neural_net.cpp.i
.PHONY : src/algorithms/neural_net.i

# target to preprocess a source file
src/algorithms/neural_net.cpp.i:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/algorithms/neural_net.cpp.i
.PHONY : src/algorithms/neural_net.cpp.i

src/algorithms/neural_net.s: src/algorithms/neural_net.cpp.s
.PHONY : src/algorithms/neural_net.s

# target to generate assembly for a file
src/algorithms/neural_net.cpp.s:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/algorithms/neural_net.cpp.s
.PHONY : src/algorithms/neural_net.cpp.s

src/core/data_structures/trie.o: src/core/data_structures/trie.cpp.o
.PHONY : src/core/data_structures/trie.o

# target to build an object file
src/core/data_structures/trie.cpp.o:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/core/data_structures/trie.cpp.o
.PHONY : src/core/data_structures/trie.cpp.o

src/core/data_structures/trie.i: src/core/data_structures/trie.cpp.i
.PHONY : src/core/data_structures/trie.i

# target to preprocess a source file
src/core/data_structures/trie.cpp.i:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/core/data_structures/trie.cpp.i
.PHONY : src/core/data_structures/trie.cpp.i

src/core/data_structures/trie.s: src/core/data_structures/trie.cpp.s
.PHONY : src/core/data_structures/trie.s

# target to generate assembly for a file
src/core/data_structures/trie.cpp.s:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/core/data_structures/trie.cpp.s
.PHONY : src/core/data_structures/trie.cpp.s

src/core/matrix.o: src/core/matrix.cpp.o
.PHONY : src/core/matrix.o

# target to build an object file
src/core/matrix.cpp.o:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/core/matrix.cpp.o
.PHONY : src/core/matrix.cpp.o

src/core/matrix.i: src/core/matrix.cpp.i
.PHONY : src/core/matrix.i

# target to preprocess a source file
src/core/matrix.cpp.i:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/core/matrix.cpp.i
.PHONY : src/core/matrix.cpp.i

src/core/matrix.s: src/core/matrix.cpp.s
.PHONY : src/core/matrix.s

# target to generate assembly for a file
src/core/matrix.cpp.s:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/core/matrix.cpp.s
.PHONY : src/core/matrix.cpp.s

src/core/utils.o: src/core/utils.cpp.o
.PHONY : src/core/utils.o

# target to build an object file
src/core/utils.cpp.o:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/core/utils.cpp.o
.PHONY : src/core/utils.cpp.o

src/core/utils.i: src/core/utils.cpp.i
.PHONY : src/core/utils.i

# target to preprocess a source file
src/core/utils.cpp.i:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/core/utils.cpp.i
.PHONY : src/core/utils.cpp.i

src/core/utils.s: src/core/utils.cpp.s
.PHONY : src/core/utils.s

# target to generate assembly for a file
src/core/utils.cpp.s:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/core/utils.cpp.s
.PHONY : src/core/utils.cpp.s

src/deployment/api.o: src/deployment/api.cpp.o
.PHONY : src/deployment/api.o

# target to build an object file
src/deployment/api.cpp.o:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/deployment/api.cpp.o
.PHONY : src/deployment/api.cpp.o

src/deployment/api.i: src/deployment/api.cpp.i
.PHONY : src/deployment/api.i

# target to preprocess a source file
src/deployment/api.cpp.i:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/deployment/api.cpp.i
.PHONY : src/deployment/api.cpp.i

src/deployment/api.s: src/deployment/api.cpp.s
.PHONY : src/deployment/api.s

# target to generate assembly for a file
src/deployment/api.cpp.s:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/deployment/api.cpp.s
.PHONY : src/deployment/api.cpp.s

src/deployment/model_server.o: src/deployment/model_server.cpp.o
.PHONY : src/deployment/model_server.o

# target to build an object file
src/deployment/model_server.cpp.o:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/deployment/model_server.cpp.o
.PHONY : src/deployment/model_server.cpp.o

src/deployment/model_server.i: src/deployment/model_server.cpp.i
.PHONY : src/deployment/model_server.i

# target to preprocess a source file
src/deployment/model_server.cpp.i:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/deployment/model_server.cpp.i
.PHONY : src/deployment/model_server.cpp.i

src/deployment/model_server.s: src/deployment/model_server.cpp.s
.PHONY : src/deployment/model_server.s

# target to generate assembly for a file
src/deployment/model_server.cpp.s:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/deployment/model_server.cpp.s
.PHONY : src/deployment/model_server.cpp.s

src/serialization/serializer.o: src/serialization/serializer.cpp.o
.PHONY : src/serialization/serializer.o

# target to build an object file
src/serialization/serializer.cpp.o:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/serialization/serializer.cpp.o
.PHONY : src/serialization/serializer.cpp.o

src/serialization/serializer.i: src/serialization/serializer.cpp.i
.PHONY : src/serialization/serializer.i

# target to preprocess a source file
src/serialization/serializer.cpp.i:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/serialization/serializer.cpp.i
.PHONY : src/serialization/serializer.cpp.i

src/serialization/serializer.s: src/serialization/serializer.cpp.s
.PHONY : src/serialization/serializer.s

# target to generate assembly for a file
src/serialization/serializer.cpp.s:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/src/serialization/serializer.cpp.s
.PHONY : src/serialization/serializer.cpp.s

tests/test_algorithms.o: tests/test_algorithms.cpp.o
.PHONY : tests/test_algorithms.o

# target to build an object file
tests/test_algorithms.cpp.o:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/test_algorithms.dir/build.make mlforge/CMakeFiles/test_algorithms.dir/tests/test_algorithms.cpp.o
.PHONY : tests/test_algorithms.cpp.o

tests/test_algorithms.i: tests/test_algorithms.cpp.i
.PHONY : tests/test_algorithms.i

# target to preprocess a source file
tests/test_algorithms.cpp.i:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/test_algorithms.dir/build.make mlforge/CMakeFiles/test_algorithms.dir/tests/test_algorithms.cpp.i
.PHONY : tests/test_algorithms.cpp.i

tests/test_algorithms.s: tests/test_algorithms.cpp.s
.PHONY : tests/test_algorithms.s

# target to generate assembly for a file
tests/test_algorithms.cpp.s:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/test_algorithms.dir/build.make mlforge/CMakeFiles/test_algorithms.dir/tests/test_algorithms.cpp.s
.PHONY : tests/test_algorithms.cpp.s

tests/test_linear_regression.o: tests/test_linear_regression.cpp.o
.PHONY : tests/test_linear_regression.o

# target to build an object file
tests/test_linear_regression.cpp.o:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/test_linear_regression.dir/build.make mlforge/CMakeFiles/test_linear_regression.dir/tests/test_linear_regression.cpp.o
.PHONY : tests/test_linear_regression.cpp.o

tests/test_linear_regression.i: tests/test_linear_regression.cpp.i
.PHONY : tests/test_linear_regression.i

# target to preprocess a source file
tests/test_linear_regression.cpp.i:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/test_linear_regression.dir/build.make mlforge/CMakeFiles/test_linear_regression.dir/tests/test_linear_regression.cpp.i
.PHONY : tests/test_linear_regression.cpp.i

tests/test_linear_regression.s: tests/test_linear_regression.cpp.s
.PHONY : tests/test_linear_regression.s

# target to generate assembly for a file
tests/test_linear_regression.cpp.s:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/test_linear_regression.dir/build.make mlforge/CMakeFiles/test_linear_regression.dir/tests/test_linear_regression.cpp.s
.PHONY : tests/test_linear_regression.cpp.s

tests/test_logistic_regression.o: tests/test_logistic_regression.cpp.o
.PHONY : tests/test_logistic_regression.o

# target to build an object file
tests/test_logistic_regression.cpp.o:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/test_logistic_regression.dir/build.make mlforge/CMakeFiles/test_logistic_regression.dir/tests/test_logistic_regression.cpp.o
.PHONY : tests/test_logistic_regression.cpp.o

tests/test_logistic_regression.i: tests/test_logistic_regression.cpp.i
.PHONY : tests/test_logistic_regression.i

# target to preprocess a source file
tests/test_logistic_regression.cpp.i:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/test_logistic_regression.dir/build.make mlforge/CMakeFiles/test_logistic_regression.dir/tests/test_logistic_regression.cpp.i
.PHONY : tests/test_logistic_regression.cpp.i

tests/test_logistic_regression.s: tests/test_logistic_regression.cpp.s
.PHONY : tests/test_logistic_regression.s

# target to generate assembly for a file
tests/test_logistic_regression.cpp.s:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/test_logistic_regression.dir/build.make mlforge/CMakeFiles/test_logistic_regression.dir/tests/test_logistic_regression.cpp.s
.PHONY : tests/test_logistic_regression.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... MLForgeLib"
	@echo "... benchmarks"
	@echo "... profiler"
	@echo "... test_algorithms"
	@echo "... test_linear_regression"
	@echo "... test_logistic_regression"
	@echo "... benchmarks/benchmarks.o"
	@echo "... benchmarks/benchmarks.i"
	@echo "... benchmarks/benchmarks.s"
	@echo "... profiling/profiler.o"
	@echo "... profiling/profiler.i"
	@echo "... profiling/profiler.s"
	@echo "... src/ai/nlp_transformer.o"
	@echo "... src/ai/nlp_transformer.i"
	@echo "... src/ai/nlp_transformer.s"
	@echo "... src/algorithms/decision.tree.o"
	@echo "... src/algorithms/decision.tree.i"
	@echo "... src/algorithms/decision.tree.s"
	@echo "... src/algorithms/linear_regression.o"
	@echo "... src/algorithms/linear_regression.i"
	@echo "... src/algorithms/linear_regression.s"
	@echo "... src/algorithms/logistic_regression.o"
	@echo "... src/algorithms/logistic_regression.i"
	@echo "... src/algorithms/logistic_regression.s"
	@echo "... src/algorithms/neural_net.o"
	@echo "... src/algorithms/neural_net.i"
	@echo "... src/algorithms/neural_net.s"
	@echo "... src/core/data_structures/trie.o"
	@echo "... src/core/data_structures/trie.i"
	@echo "... src/core/data_structures/trie.s"
	@echo "... src/core/matrix.o"
	@echo "... src/core/matrix.i"
	@echo "... src/core/matrix.s"
	@echo "... src/core/utils.o"
	@echo "... src/core/utils.i"
	@echo "... src/core/utils.s"
	@echo "... src/deployment/api.o"
	@echo "... src/deployment/api.i"
	@echo "... src/deployment/api.s"
	@echo "... src/deployment/model_server.o"
	@echo "... src/deployment/model_server.i"
	@echo "... src/deployment/model_server.s"
	@echo "... src/serialization/serializer.o"
	@echo "... src/serialization/serializer.i"
	@echo "... src/serialization/serializer.s"
	@echo "... tests/test_algorithms.o"
	@echo "... tests/test_algorithms.i"
	@echo "... tests/test_algorithms.s"
	@echo "... tests/test_linear_regression.o"
	@echo "... tests/test_linear_regression.i"
	@echo "... tests/test_linear_regression.s"
	@echo "... tests/test_logistic_regression.o"
	@echo "... tests/test_logistic_regression.i"
	@echo "... tests/test_logistic_regression.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/djrussell23/Documents/repos/reactor-core && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

